# Generated by Django 4.1.5 on 2023-01-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_userprofile_owned_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='owned_restaurant',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owned_restaurant',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.restaurant'),
        ),
    ]
