# Generated by Django 4.1.5 on 2023-01-28 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_userprofile_owned_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='owned_restaurant',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='owned_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurant'),
        ),
    ]
