# Generated by Django 4.1.5 on 2023-01-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_remove_userprofile_owned_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-img/'),
        ),
    ]
