# Generated by Django 4.1.5 on 2023-01-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_order_orderitem_order_products_order_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('nowe', 'nowe'), ('w trakcie', 'w trakcie'), ('gotowe', 'gotowe'), ('wysłane', 'wysłane')], default='nowe', max_length=255),
        ),
    ]
